import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { cn } from '@/lib/utils'
import { FilterProvider } from "@/contexts/filter";
import { DeleteProvider } from "@/contexts/delete";
import { CartProvider } from "@/contexts/cart";
import { AddressProvider } from "@/contexts/address";
import { ThemeProvider } from "@/contexts/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className={`h-full`}>
      <body className={cn("relative h-full font-sans antialiased", inter.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className='relative flex flex-col min-h-screen '>
            <Header />
            <div className="flex-grow flex-1">
              <FilterProvider>
                <DeleteProvider>
                  <CartProvider>
                    <AddressProvider>
                      {children}
                    </AddressProvider>
                  </CartProvider>
                </DeleteProvider>
              </FilterProvider>
            </div>
            {/* <Footer /> */}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
